create database if not exists customer_behavior;
use customer_behavior;
select*from customer;

# Business insights question:-

# (Q1).Which cateogry generates highest revenue?
select category,
round(sum(purchase_amount),2) as highest_revenue 
from customer
group by category
order by highest_revenue desc;

-- ? Business problem :- company does not know which category contributes most to revenue
-- impact:-
           -- help prioritize high performing categories
           -- optimizes inventory planning:-means jo jyda sell ho rha hai usko hardam stock me rakhne ka 
           -- improves marketing ROI(Return on Investment):-jitna paisa lagaya uske badle kitna fayda hua.
		
# (Q2) Are discounts actually increasing purchase value?
select discount_applied,
round(sum(purchase_amount),2) as highest_revenue,
round(avg(purchase_amount),2) as highest_revenue
from customer
group by discount_applied;

-- ? Business problem :-Discounts may reduce profit without increasing sales
-- impact:-
         -- identify effectiveness of the discounts
         -- Reduce unnecessary discounts costs
         -- improve profit margins
		
# (Q3) What is the total revenue generated by male and female cutomer?
select gender,
round(sum(purchase_amount),2) as highest_revenue 
from customer
group by gender
order by highest_revenue desc;

-- ? Business problem :- lack of understanding of revenue contribution byb gender segments
-- impact:-
          -- Helps design targeted marketing campagins
          -- Improves customer segementation strategy
          -- Enhance personalization efforts

# (Q4) Which customer used a discount but still spent more then the average purchase amount?
select customer_id,purchase_amount,discount_applied from customer
where discount_applied='yes' and purchase_amount >(select avg(purchase_amount) from customer) 
limit 10;

-- ? Business problem :- Company cannot identify high-spending customers who are also discounts user.
-- impact:-
          -- Identifies premium discount-sensitive customers
          -- Enables targeted discount campaigns
          -- improves customer retention and revenue
          
# (Q5) Which are the top/bottom 5 products with the highest avarage review rating?
select item_purchased,
round(avg(review_rating),2) as avg_ratings
from customer 
group by item_purchased
order by avg_ratings desc limit 5;

select item_purchased,
round(avg(review_rating),2) as avg_ratings
from customer 
group by item_purchased
order by avg_ratings asc limit 5;

-- ? Business problem :- No Visibility into product performance based on customer satiaction.
-- imapct:- 
         -- promotes high-performing products
         -- improve low-rated products
         -- enhance customer experience
         
#(Q6). Average purchase:Standard vs Express shipping
Select shipping_type,
count(distinct customer_id) as order_placed,
round(avg(purchase_amount),2) as avg_purchase,
round(sum(purchase_amount),2) as revenue
from customer 
-- where shipping_type in ('standard','express')
group by shipping_type
order by revenue desc;
         
-- ? Business problem :-Unclear if fatser shipping leads to higher spending.
-- imapct:- 
         -- Helps optimize shipping pricing strategy
         -- Encourages premium shipping adoption
         -- Increse average order value
         
  # (Q7)   Do subscribe customers spend more? compare average speed and total revenue between subscribers and non-subscribers
  select subscription_status,
	count(customer_id) as users,
    round(avg(purchase_amount),2) as avg_revenue,
    round(sum(purchase_amount),2) as total_revenue
  from customer 
  group by subscription_status
  order by total_revenue desc;
         
-- ? Business problem :-The effectiveness of subscription programs is unknown
-- imapct:-        
         -- validates subscription model performance
         -- improves customer loyalty programs
         -- Increse customer lifetime value(CLV)

# (Q8)top 5 products with highest discount usage %?
select item_purchased,
     count(item_purchased)as total_number_of_times_sold,
     count(case when discount_applied='yes' then 1 end)as number_of_times_sold_when_discount_applied,
	 count(case when discount_applied='yes' then 1 end)*100.0/count(*) as discount_percent
from customer 
group by item_purchased
order by discount_percent desc limit 5;
         
-- ? Business problem :-Some products may be overly dependent on discounts
-- imapct:-   
         -- identifies discount-driven products
         -- helps optimize pricing strategy
         -- reduce profit margin loss
         
# (Q9) Segment customer into new returning and loyal based on their total number of previous purchase
# and show the count of each segment?

select 
     case
         when previous_purchases='0' then 'new customer'
         when previous_purchases between 1 and 15 then 'returning customer'
	 else 'loyal customers'
end as customer_segment,
count(*) as customer_count
from customer
group by case
		   when previous_purchases='0' then 'new customer'
           when previous_purchases between 1 and 15 then 'returning customer'
	 else 'loyal customers'
end;


-- ? Business problem :- Lack of customer segmenstation leads to generic strategies
-- imapct:- 
          -- Enables personlaizes marketing
          -- Improves retention strategies
          -- increase conversion rates

#(Q10).What are the top 3 most purchased products within each category?
with cte as
( 
select
      category,
      item_purchased,
      count(item_purchased) as most_purchased,
      rank()over(partition by category order by count(item_purchased)desc) as rnk
from customer 
group by category,item_purchased
)
select*from cte
where rnk<=3;

-- ? Business problem :-The company doesn't know top-performing products within categories.
-- imapct:- 
         -- improves product placement and recommendations
         -- Help inventory optimization
         -- increase sales through best-selller

#(Q11) Are customer who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select
      case
          when previous_purchases>5 then 'repeat buyer'
          else 'normal buyers'
	  end as customer_type,
      subscription_status,
      count(*) as customer_count,
      count(*)*100.0/sum(count(*))over(partition by  case
          when previous_purchases>5 then 'repeat buyer'
          else 'normal buyers'
	  end) as percent
from customer
group by  
        case
          when previous_purchases>5 then 'repeat buyer'
          else 'normal buyers'
end ,subscription_status;

-- ? Business problem :- Unclear relationship between loyality and subscription
-- imapct:- 
        -- improves subscription targeting
        -- increase conversion to paid progress
        -- increase customer retention strategy
        
#(Q12).What is the revenue contribution of each age group?
select 
      case 
          when age between 18 and 25 then '18-25'
          when age between 26 and 35 then '26-35'
          when age between 36 and 50 then '36-50'
          else '51+'
		end as age_group,
round(sum(purchase_amount),2) as total_revenue
from customer 
group by  case 
          when age between 18 and 25 then '18-25'
          when age between 26 and 35 then '26-35'
          when age between 36 and 50 then '36-50'
          else '51+'
		end
        order by total_revenue desc

-- ? Business problem :- No visibility into which age group contributes most to revenue.
 -- imapct:-   
          -- Enable age-based targeting
          -- Enhances marketing efficiency 